### ISSUE TITLE
Not working when bundled for production

### ISSUE THREAD

**Issue by diegosiao** [mozmorris/react-webcam#163] opened 2019-10-10 04:11 UTC
While in development the component works perfectly as expected, but deploying to production causes the component to show a blank square in the media screen.

The **onUserMediaError** callback is never called.

> onUserMediaError={() => {
>                         this.setState({
>                             cameraError: true
>                         });
>                     }}

**Comment by mozmorris** [comment] 2019-10-10 06:50
Thank you for this report @diegosiao 

To help you with this, we need further information. Have you got a URL I can check? Even better, a basic example of your project as a Github repository would be very helpful.

Without nothing else to go on, it's hard to say what the issue is.

**Comment by diegosiao** [comment] 2019-10-10 14:06
Thanks for your response! 

There is no much data or code because my implementation is as simple as the one saw on documentation, and it is working fine with no production related bundle actions such as uglyfying, compression and etc.

Since it only happens after a deploy, I imagine you could have a clue or maybe it is a known issue, maybe related to webpack in some form?

Anyway, I appreciate any help and I continue to search for a solution. I will be back to the code later and I will post it here.

**Comment by mozmorris** [comment] 2019-10-10 14:09
Are you serving your application over SSL?

**Comment by diegosiao** [comment] 2019-10-10 14:14
No, not yet.

**Comment by mozmorris** [comment] 2019-10-10 14:14
That would be the problem.

`Note: Browsers will throw an error if the page is loaded from insecure origin. I.e. Use https.`

**Comment by mozmorris** [comment] 2019-10-11 07:18
@diegosiao I'm going to close this. Your issue will be fixed once you serve your application over SSL.

Feel free to open another issue if you have any more problems, thanks.

**Closed by mozmorris** 2019-10-11 07:18 UTC
Labels: needs more info

**Comment by diegosiao** [comment] 2019-10-11 11:46
I will suggest to include this information in documentation, as a short note.
Thank you!

**Comment by mozmorris** [comment] 2019-10-11 12:01
It's already at the top of the README 😉

**Comment by diegosiao** [comment] 2019-10-11 12:08
Indeed. Sorry 🤦‍♂️
