### ISSUE TITLE
If webcam is inside a modal, and the modal is closed soon after the modal is opened, the webcam does not stop

### ISSUE THREAD

**Issue by piltsen** [mozmorris/react-webcam#86] opened 2018-06-16 17:30 UTC
Hello, 

Thanks for the wrapper, it worked really well for our purpose. 

We have, however, found a small inconsistency. If we put the webcam inside a modal, and for whatever reason we close the Modal before the camera had the time to initialise, the camera stays 'on'. Almost in a locked state. If we try to open the Modal again, the camera does not show, because it is busy already with another process (I can tell that because Chrome shows a 'recording' icon on the tab and also the camera stays with the light on as if it was working). The only alternative is to refresh the browser. 

Is there any method that we can plug to a callback to shut the webcam down? 

Many thanks

**Comment by mozmorris** [comment] 2018-06-28 08:33
@piltsen do you have a repo where I can reproduce the issue?

**Comment by Valerio69** [comment] 2018-08-14 06:51
Hello, first of all thanks for this components! 👍 
This happened to me as well using the SweetAlert (modal Alert) from Material UI Pro components 
For example when the user open the Modal Alert and close it before he "Allow" the browser to use the webcam. 

```
showWebcamAlert() {
    this.hideAlert();

    const videoConstraints = {
      width: 1280,
      height: 720,
      facingMode: 'user',
    };

    this.setState({
      alert: (
        <SweetAlert
          showCancel
          style={{ display: "block", marginTop: "-300px" }}
          title='Webcam'
          onConfirm={() => this.captureScreenshot()}
          onCancel={() => this.hideAlert()}
          confirmBtnText="Capture"
          confirmBtnCssClass={
            this.props.classes.button + " " + this.props.classes.info
          }
          cancelBtnCssClass={
            this.props.classes.button + " " + this.props.classes.danger
          }
        >
          <Webcam
            style={{
              maxWidth: '100%',
              maxHeight: '100%',
              width: 'auto',
              height: 'auto'
            }}
            screenshotQuality={1}
            audio={false}
            ref={this.setRef}
            onUserMedia={this.onUserMediaChange}
            onFailure={this.onFailureWebcam}
            screenshotFormat="image/jpeg"
            videoConstraints={videoConstraints}
          />
        </SweetAlert>
      )
    });
}
```

When that happen the 'componentWillUnmount' event is never setting **userMediaRequested** to false because both 
**Webcam.mountedInstances.length === 0 && this.state.hasUserMedia** are true.
So to fix this problem I moved **Webcam.userMediaRequested = false;** before the if statement to set the **userMediaRequest** to false every time the component unmount.

```
componentWillUnmount() {
    console.log('Webcam componentWillUnmount');
    const index = Webcam.mountedInstances.indexOf(this);
    Webcam.mountedInstances.splice(index, 1);
    
    // line Moved here
    Webcam.userMediaRequested = false;
    
    if (Webcam.mountedInstances.length === 0 && this.state.hasUserMedia) {
      if (this.stream.stop) {
        this.stream.stop();
      } else {
        if (this.stream.getVideoTracks) {
          this.stream.getVideoTracks().map(track => track.stop());
        }
        if (this.stream.getAudioTracks) {
          this.stream.getAudioTracks().map(track => track.stop());
        }
      }
      // Webcam.userMediaRequested = false;
      window.URL.revokeObjectURL(this.state.src);
    }
  }
```

**Comment by mozmorris** [comment] 2018-08-14 08:48
@Valerio69 thank you for the PR and your follow up comment here. It's appreciated.

Quick question before I dig deeper:

> ...'componentWillUnmount' event is never setting userMediaRequested to false because both Webcam.mountedInstances.length === 0 && this.state.hasUserMedia are true.

If this were the case, userMediaRequested would still end up being set to false. Did you mean one of those conditionals is false?

**Comment by Valerio69** [comment] 2018-08-14 16:39
yes I'm sorry, I edited my answer.
"**Webcam.mountedInstances.length === 0** is true but "**this.state.hasUserMedia**" is false.

**Comment by mozmorris** [comment] 2018-08-14 19:30
Okay, I can see how your solution solves the issue when you reopen the modal. Let me test it and I'll merge it. I can see there being an issue though when there are multiple instances of the component on the page. Although I have a suspicion that functionality doesn't truly work even though the demo using multiple instances works fine. 😉

**Closed** 2018-09-15 08:56 UTC
